### ISSUE TITLE
ZConomy Broken in latest Build 41

### ISSUE THREAD

**Issue by Mackinz** [phyreman/ZConomy#1]
Here is the log file. I started a new game and went around adding stuff to my inventory. Note the over 2000 instances of "Error, container already has id"

[console.txt](https://github.com/phyreman/ZConomy/files/7036174/console.txt)

**Comment by phyreman** [comment]
It looks like they've changed how items are distributed to containers, I'll start working on a fix.

**Comment by phyreman** [comment]
This should be fixed now.
